In [ ]:
#️Задание 4.a
import numpy as np

In [218]:
#️Задание 4.b
import numpy as np
a = np.zeros(10)
print(a);

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#️Задание 4.c
import numpy as np
a = np.ones(10)
print(a)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#️Задание 4.d
import numpy as np
a=np.full(10, 5)
print(a)

[5 5 5 5 5 5 5 5 5 5]


In [219]:
#️Задание 4.e
import numpy as np
a=np.arange(10,50,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#️Задание 4.f
import numpy as np
a=np.arange(10,50,2)
print(a)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#️Задание 4.g
import numpy as np
a=np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [220]:
#️Задание 4.h
import numpy as np
a = np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#️Задание 4.i
import numpy as np
a = np.random.randint(0,1,1)
print(a)

[0]


In [221]:
#️Задание 4.j
import numpy as np
a = np.random.normal(0,1,25)
print(a)

[-0.65331612  0.10623762  0.15109218  0.18211535 -2.14442261 -0.59102414
  0.69357262  0.58057913 -1.82706875 -0.99756263  1.50936649  2.01498102
  1.10246339  0.65055212 -1.29408129 -0.00732201  0.5089516   1.0753349
  0.863776    0.14154465 -1.11696188  0.33240124  2.20048501  0.00579843
  3.62955781]


In [88]:
#️Задание 4.k
import numpy as np
a=np.arange(0.01,1.01,0.01).reshape((10,10))
print (a)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [222]:
#️Задание 4.l
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [223]:
#️Задание 4.l
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = mat[2: , 1:]
print(mat)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [171]:
#️Задание 4.m
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = mat[3::4, -1::1]
print (mat)

[[20]]


In [207]:
#️Задание 4.n
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = mat[-1: , -5::]
print (mat)

[[21 22 23 24 25]]


In [210]:
#️Задание 4.o
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = mat[-1: , -5::]
print (mat)

[[21 22 23 24 25]]


In [211]:
#️Задание 4.p
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = mat[-2: , -5::]
print (mat)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [215]:
#️Задание 4.q
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = np.sum(mat)
print(mat)

325


In [ ]:
#️Задание 4.r

In [216]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = np.std(mat)
print(mat)

7.211102550927978


In [217]:
#️Задание 4.s
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat = np.sum(mat, axis=0) 
print(mat)

[55 60 65 70 75]
